spring:
  application:
    name: ReleasePilot
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-retries: 5
          initial-interval: 1s
          multiplier: 2.0
          max-interval: 30s
        default-requeue-rejected: false

---
spring:
  config:
    activate:
      on-profile: read-model-projector
  main:
    web-application-type: none

---
spring:
  config:
    activate:
      on-profile: audit-log-consumer
  main:
    web-application-type: none

---
spring:
  config:
    activate:
      on-profile: outbox-relay
  main:
    web-application-type: none

---
spring:
  config:
    activate:
      on-profile: release-notes-agent-consumer
  main:
    web-application-type: none
